language: node_js
install:
  - npm install -g react-native-cli
  - yarn
script:
  - yarn eslint:ci
  - yarn test:coverage
after_success:
  - npm install -g codecov
  - codecov
notifications:
  email: false
